name: Daily Email Sender

on:
  schedule:
    # Run at 9:00 AM UTC (adjust as needed)
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      email_template_path:
        description: 'Path to email template file'
        required: false
        default: 'email-templates/welcome_email_1_thanks.html'

jobs:
  send-daily-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create logs directory
        run: mkdir -p email-logs

      - name: Run daily email sender
        run: node daily-email-sender.js ${{ github.event.inputs.email_template_path || 'email-templates/welcome_email_1_thanks.html' }}
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: email-logs
          path: email-logs/
          retention-days: 7
